package test.model;

public class ClazzTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.id
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class.class_name
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.id
     *
     * @return the value of t_class.id
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.id
     *
     * @param id the value for t_class.id
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class.class_name
     *
     * @return the value of t_class.class_name
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class.class_name
     *
     * @param className the value for t_class.class_name
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }
}