package cn.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.ClazzTest;
import test.model.ClazzTestExample;

public interface ClazzTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    long countByExample(ClazzTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int deleteByExample(ClazzTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int insert(ClazzTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int insertSelective(ClazzTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    List<ClazzTest> selectByExample(ClazzTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    ClazzTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") ClazzTest record, @Param("example") ClazzTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int updateByExample(@Param("record") ClazzTest record, @Param("example") ClazzTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int updateByPrimaryKeySelective(ClazzTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class
     *
     * @mbg.generated Thu May 16 23:18:34 CST 2019
     */
    int updateByPrimaryKey(ClazzTest record);
}